seed: 42

MLP:
  d_layers: 
    - 64
    - 32
  dropout: 0.5

TabTransformer:
  dim: 32
  depth: 6
  heads: 8
  attn_dropout: 0.08
  ff_dropout: 0.3

ModernNCA:
  dim: 128
  dropout: 0.1
  temperature: 1

FourierFeatures:
  n_frequencies: 32
  frequency_scale: 10

BinningFeatures:
  n_bins: 50
  delta_scale: 30
  delta_min: 0.1
  delta_max: 100

ComboFeatures:
  n_frequencies: 32
  frequency_scale: 10
  n_bins: 50
  delta_scale: 30
  delta_min: 0.1
  delta_max: 100


training:
  batch_size: 64
  epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0001
